### ISSUE TITLE
Docs: Feedback for Java Client

### ISSUE THREAD

**Issue by blackthe1st** [hazelcast/imdg-docs#277] opened 2021-09-12 09:31 UTC
Hi, I have some feedback about [this page](https://github.com/hazelcast/imdg-docs/edit/v/4.2/docs/modules/clients/pages/java.adoc)

In listening event section, clientDisconnected event is not called when "client.shutDown()"

**Comment by sancar** [comment] 2021-09-22 14:04
Hi @blackthe1st 

I have run the following code and both clientConnected/disconnected worked 

```
  HazelcastInstance instance = Hazelcast.newHazelcastInstance();

        instance.getClientService().addClientListener(new ClientListener() {
            @Override
            public void clientConnected(Client client) {
                System.out.println("CONNECTED " + client);
            }

            @Override
            public void clientDisconnected(Client client) {
                System.out.println("DISCONNECTED " + client);
            }
        });

        HazelcastInstance client = HazelcastClient.newHazelcastClient();

        client.shutdown();
 ```
 
 In which case, you don't see client-disconnected ? Do you have a reproducer test ?
 What is the version of hazelcast that you are using ? 
 
 Could  it be the case that it is called late ? Asking it because we had this bug and fixed in a later version. 
https://github.com/hazelcast/hazelcast/issues/18318

**Comment by sancar** [comment] 2021-09-27 08:49
@blackthe1st Did you have chance to read my comment ?

**Comment by sancar** [comment] 2021-10-04 08:11
@blackthe1st I am closing the issue due to inactivity.  Don't hesitate to bring this up again if you think it is not clear enough.
We prefer getting questions on the google group or slack community channel first to clarify if it was the intended behavior or not before opening an issue. 
https://groups.google.com/g/hazelcast
https://slack.hazelcast.com/

**Closed by sancar** 2021-10-04 08:11 UTC
